approvals:
  ignore: pr_opener  # cannot approve a PR you opened
  pattern: "(:\\+1:|:thumbsup:|:shipit:|lgtm|LGTM)"  # :+1:, :thumbsup:, :shipit:, lgtm or LGTM
  minimum: 3  # Need UX, engineering and a11y approval
  groups:
    # at least 1 approval from UX
    ux:
      minimum: 1
      from:
        users:
          - chris-mike
          - roderickmorales
          - lizc577
    # at least 1 approval from FedX engineers
    engineering:
      minimum: 1
      from:
        users:
          - andy-armstrong
          - AlasdairSwan
          - alisan617
          - bjacobel
          - dsjen
    # at least 1 approval from a11y
    a11y:
      minimum: 1
      from:
        users:
          - clrux
          - cptvitamin
